// Taken from FSD.gov> Home > Knowledge Base >  Entity Registration >  Frequently Asked Questions
// https://www.fsd.gov/gsafsd_sp?id=gsafsd_kb_category&kb_category=7ae0cb0c1b4f64108aa3a8eae54bcb0e
export let KnowledgeBaseArticles = [
                {
                    "short_description": "Why do I see a \"non-registered Unique Entity ID\" in my entity list?",
                    "sys_view_count": 19,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-04-02 00:07:33",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Why do I see a \"non-registered Unique Entity ID\" in my entity list?",
                    "sys_id": "03f360271bde01d0937fa64ce54bcb85",
                    "number": "KB0017162",
                    "_table_name": "kb_knowledge",
                    "text": "The entity list shows you all the Unique Entity IDs with which you have a role. This can include Unique Entity IDs that represent entities lower in your organizational hierarchy, i.e., child entities, which you may not have registered yet to do business...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How long does it take to receive a CAGE Code?",
                    "sys_view_count": 309,
                    "author": "Lilla Jimmerson",
                    "rating": "4",
                    "sys_updated_on": "2022-09-21 20:21:35",
                    "published": "2022-09-21",
                    "type": "kb_article",
                    "title": "How long does it take to receive a CAGE Code?",
                    "sys_id": "04b5fe461b8ed15006b09796bc4bcbde",
                    "number": "KB0016994",
                    "_table_name": "kb_knowledge",
                    "text": "You can review answers to frequently asked questions about the CAGE Code assignment process here . It can take up to ten business days to process a CAGE Code request with a new SAM entity registration. You can use the Check Status button on the home page...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why can't I update the POCs on my registration?",
                    "sys_view_count": 298,
                    "author": "Lilla Jimmerson",
                    "rating": "2.13",
                    "sys_updated_on": "2022-04-02 00:09:37",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Why can't I update the POCs on my registration?",
                    "sys_id": "04f3889b1b1a0d90937fa64ce54bcbcd",
                    "number": "KB0056336",
                    "_table_name": "kb_knowledge",
                    "text": "If you had an entity registered in SAM.gov before April 4, 2022, then the first time you update your entity after that date, you will not have the option to update points of contact (POCs) only. You will only have the option to update or renew your entire...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Starting Entity Validation as a New Entity in SAM.gov",
                    "sys_view_count": 795,
                    "author": "Jared Davidson",
                    "rating": "3.5",
                    "sys_updated_on": "2022-09-06 12:46:29",
                    "published": "2022-09-06",
                    "type": "kb_article",
                    "title": "Starting Entity Validation as a New Entity in SAM.gov",
                    "sys_id": "05c27fbb1b6119d00ca4a97ae54bcb12",
                    "number": "KB0060383",
                    "_table_name": "kb_knowledge",
                    "text": "These are the instructions for A. Entity New to SAM.gov. If you don’t have a Unique Entity ID or a registration, this is the first step in the entity validation process.  If you have an active or inactive SAM.gov registration that you need to renew or...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What Should I Do if My Entity is in the Results and All Info is Correct?",
                    "sys_view_count": 759,
                    "author": "Jared Davidson",
                    "rating": "2.4",
                    "sys_updated_on": "2022-10-07 18:00:43",
                    "published": "2022-10-07",
                    "type": "kb_article",
                    "title": "What Should I Do if My Entity is in the Results and All Info is Correct?",
                    "sys_id": "0788ba1c1b1255d0c5c4dd39bc4bcb76",
                    "number": "KB0060387",
                    "_table_name": "kb_knowledge",
                    "text": "These are the instructions for 2.What to Do if Your Entity is in the Results and All Info is Correct Previous Entity Validation Steps:  KB0060383 Starting Entity Validation as a New Entity in SAM.gov KB0060384 Starting Entity Validation as an Existing...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "I am an entity administrator and received an email about a registration request. What do I do?",
                    "sys_view_count": 35,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-10-03 17:54:37",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "I am an entity administrator and received an email about a registration request. What do I do?",
                    "sys_id": "0827c4c21b9edd146e2dea02f54bcb81",
                    "number": "KB0017320",
                    "_table_name": "kb_knowledge",
                    "text": "You should proceed to SAM.gov and log in with your entity administrator account. Navigate to your Workspace, then select Pending Hierarchy Registration Requests. You will see all outstanding requests listed on this page. You should review the user and...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I filter entity registrations by product or service code? ",
                    "sys_view_count": 34,
                    "author": "Jared Davidson",
                    "rating": "3",
                    "sys_updated_on": "2022-10-03 17:56:54",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "How do I filter entity registrations by product or service code? ",
                    "sys_id": "08a70c4a1b9edd146e2dea02f54bcbee",
                    "number": "KB0029902",
                    "_table_name": "kb_knowledge",
                    "text": "Log in to your account and follow the instructions below: Navigate to the header menu of any page and select “Search.” From the search page, navigate to the left-side bar. Select the “plus” icon to the right of “Select Domain,” then select “Entity Registration...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Quick Start Guide for Getting a Unique Entity ID",
                    "sys_view_count": 5008,
                    "author": "Jared Davidson",
                    "rating": "2.57",
                    "sys_updated_on": "2022-04-02 20:32:12",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Quick Start Guide for Getting a Unique Entity ID",
                    "sys_id": "0a06493e1bee8d54937fa64ce54bcb93",
                    "number": "KB0049214",
                    "_table_name": "kb_knowledge",
                    "text": "Refer to the Guide to Getting a Unique Entity ID if you want to get a Unique Entity ID (SAM) for your organization without having to complete a full entity registration. If you only conduct certain types of transactions, such as reporting as a sub-awardee,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I view the quick start guides for entity registrations? ",
                    "sys_view_count": 3482,
                    "author": "Jared Davidson",
                    "rating": "3.17",
                    "sys_updated_on": "2022-05-16 18:54:10",
                    "published": "2022-05-16",
                    "type": "kb_article",
                    "title": "How do I view the quick start guides for entity registrations? ",
                    "sys_id": "0ba157f01ba3c5103565ed3ce54bcbcf",
                    "number": "KB0029897",
                    "_table_name": "kb_knowledge",
                    "text": "There are a number of helpful Quick Start Guides depending on the type of entity you are registering or whether you need to update an entity that is already registered. Click the links below to download and view each guide:  Quick Start Guide for Contract...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "State or Country of Incorporation ",
                    "sys_view_count": 192,
                    "author": "Lilla Jimmerson",
                    "rating": "5",
                    "sys_updated_on": "2022-08-10 12:47:54",
                    "published": "2022-08-10",
                    "type": "kb_article",
                    "title": "State or Country of Incorporation ",
                    "sys_id": "0c3160651b189d500944ece0f54bcbb6",
                    "number": "KB0059570",
                    "_table_name": "kb_knowledge",
                    "text": "State or Country of Incorporation is the location where you legally began doing business.  For incorporated entities, it is the state (or country, for non-US entities) where they were incorporated.  For non-incorporated entities, this could be where your...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I create a FSD account? ",
                    "sys_view_count": 402,
                    "author": "Lilla Jimmerson",
                    "rating": "2.43",
                    "sys_updated_on": "2022-04-02 00:07:12",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I create a FSD account? ",
                    "sys_id": "0cefa1af1b5a09d0cc45ea04bc4bcb9a",
                    "number": "KB0017825",
                    "_table_name": "kb_knowledge",
                    "text": "To create a Federal Service Desk (FSD) account, follow the steps below: Go to the FSD.gov website. At the beginning of the page, select “Sign In.” Select “Sign In” again in the popup that appears to accept the U.S. government system terms of use.  From...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Getting Started with Entity Registration",
                    "sys_view_count": 15592,
                    "author": "Jared Davidson",
                    "rating": "2.62",
                    "sys_updated_on": "2022-10-06 13:53:59",
                    "published": "2022-10-06",
                    "type": "kb_article",
                    "title": "Getting Started with Entity Registration",
                    "sys_id": "0dbce6b61b165954860e62cfe54bcbf8",
                    "number": "KB0039524",
                    "_table_name": "kb_knowledge",
                    "text": "Here is a list of FAQs and Quick Start Guides that will help you through the process of registering a new entity: Unable to find a matching entity when asked to enter or validate my entity information Definition of an entity Quick Start Guide for Grant...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why can I see multiple records for the same entity with the same Unique Entity ID but with different statuses?",
                    "sys_view_count": 90,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-04-02 00:10:08",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Why can I see multiple records for the same entity with the same Unique Entity ID but with different statuses?",
                    "sys_id": "0dc3f65e1b6a4d546e2dea02f54bcb23",
                    "number": "KB0056865",
                    "_table_name": "kb_knowledge",
                    "text": "If you get a Unique Entity ID for an entity without registering, you will see your entity with the status “ID Assigned.”  If you then register that entity, you will see your entity with the status “Active Registration.” These two records may appear simultaneou...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I assign my payments to go to another assignee or another bank account for my company?",
                    "sys_view_count": 38,
                    "author": "Lilla Jimmerson",
                    "rating": "2.67",
                    "sys_updated_on": "2022-04-02 00:07:34",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I assign my payments to go to another assignee or another bank account for my company?",
                    "sys_id": "132068eb1b1e01d0937fa64ce54bcb0a",
                    "number": "KB0016399",
                    "_table_name": "kb_knowledge",
                    "text": "If a contractor assigns their payments to another source, the contract needs to be modified to identify the assignee. That identification needs to include the assignee's Unique Entity ID or CAGE code. The finance office should review that section of the...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Is the Unique Entity ID unique like the DUNS Numbers are?",
                    "sys_view_count": 471,
                    "author": "Lilla Jimmerson",
                    "rating": "3.11",
                    "sys_updated_on": "2022-04-02 00:10:13",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Is the Unique Entity ID unique like the DUNS Numbers are?",
                    "sys_id": "139cef6b1bc68dd40ca4a97ae54bcbfa",
                    "number": "KB0045980",
                    "_table_name": "kb_knowledge",
                    "text": "Yes. Unique Entity IDs are unique like DUNS Numbers are. Entity Validation Service (EVS) is a service that independently verifies the uniqueness of an entity. SAM.gov uses an EVS to verify that no existing identifier exists for the legal business name...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Help For the Transition from DUNS to Unique Entity ID",
                    "sys_view_count": 25981,
                    "author": "Jared Davidson",
                    "rating": "2.55",
                    "sys_updated_on": "2022-09-29 17:15:51",
                    "published": "2022-09-29",
                    "type": "kb_article",
                    "title": "Help For the Transition from DUNS to Unique Entity ID",
                    "sys_id": "14c7dfa81b9659d0c5c4dd39bc4bcb0f",
                    "number": "KB0046482",
                    "_table_name": "kb_knowledge",
                    "text": "Here is a list of resources to help you through the transition from DUNS Number to Unique Entity ID, based on the work you do in SAM.gov. You can also find general information about the transition in the sections below. *New* FAQs updated and more added...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why do I have a ticket in FSD.gov for my entity validation incident? ",
                    "sys_view_count": 546,
                    "author": "Lilla Jimmerson",
                    "rating": "3",
                    "sys_updated_on": "2022-05-13 14:03:55",
                    "published": "2022-05-13",
                    "type": "kb_article",
                    "title": "Why do I have a ticket in FSD.gov for my entity validation incident? ",
                    "sys_id": "14ca408f1b178d90fe314000f54bcb53",
                    "number": "KB0056340",
                    "_table_name": "kb_knowledge",
                    "text": "When you create an incident in SAM.gov, we also create an FSD ticket.  The purpose of the FSD ticket is to enable communication between our agents and you as they review your documentation.  Although the incident is managed through the FSD.gov ticket,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What is an entity hierarchy?",
                    "sys_view_count": 87,
                    "author": "Lilla Jimmerson",
                    "rating": "3",
                    "sys_updated_on": "2022-04-02 00:06:18",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What is an entity hierarchy?",
                    "sys_id": "1727adef1b1609d0cc45ea04bc4bcb37",
                    "number": "KB0056344",
                    "_table_name": "kb_knowledge",
                    "text": "An entity hierarchy is a relationship between entities in which one entity is a “child” of another entity known as the “parent.” For example, an academic department may be part of a university’s hierarchy, or a division may be part of a corporation’s...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I update the banking information on my SAM.gov entity registration?",
                    "sys_view_count": 1983,
                    "author": "Lilla Jimmerson",
                    "rating": "2.83",
                    "sys_updated_on": "2022-04-02 00:08:01",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I update the banking information on my SAM.gov entity registration?",
                    "sys_id": "1773ccc91b9e4d10937fa64ce54bcb56",
                    "number": "KB0016842",
                    "_table_name": "kb_knowledge",
                    "text": "Please follow the steps below to update banking information on an entity registration in SAM.gov: Navigate to SAM.gov and sign in to your account. After signing in, the system will redirect you to your SAM.gov Workspace. In the workspace, find the Entity...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Are international organizations required to register their entity in SAM.gov?",
                    "sys_view_count": 85,
                    "author": "Lilla Jimmerson",
                    "rating": "2",
                    "sys_updated_on": "2022-05-12 13:16:51",
                    "published": "2022-05-12",
                    "type": "kb_article",
                    "title": "Are international organizations required to register their entity in SAM.gov?",
                    "sys_id": "194695221bfe4d983565ed3ce54bcbbb",
                    "number": "KB0016380",
                    "_table_name": "kb_knowledge",
                    "text": "Any potential awardee needs an entity registration in SAM.gov. International entities may follow the step-by-step instructions in the Quick Start Guide for International Registrations to register in SAM.gov.  ",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I confirm my financial information on my entity registration if it is partially hidden?",
                    "sys_view_count": 57,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-08-26 14:58:34",
                    "published": "2022-08-26",
                    "type": "kb_article",
                    "title": "How do I confirm my financial information on my entity registration if it is partially hidden?",
                    "sys_id": "1962f3211bed1d50fe314000f54bcbe2",
                    "number": "KB0017434",
                    "_table_name": "kb_knowledge",
                    "text": "For security purposes,  the Financial information is masked from view for all users. You will only be able to confirm the hidden information during an update. If you discover the banking information is accurate and you have no changes to make, you will...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What happened to the DUNS Number?",
                    "sys_view_count": 1688,
                    "author": "Lilla Jimmerson",
                    "rating": "4.02",
                    "sys_updated_on": "2022-04-02 00:08:50",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What happened to the DUNS Number?",
                    "sys_id": "199144d31bd60d90937fa64ce54bcb3e",
                    "number": "KB0056335",
                    "_table_name": "kb_knowledge",
                    "text": "On April 4, 2022, the federal government stopped using the DUNS Number as a unique identifier for entities and switched to a Unique Entity ID generated by SAM.gov. The new Unique Entity ID was assigned to all active and inactive registrations in SAM.gov...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What entity registration fields are available for different roles?",
                    "sys_view_count": 183,
                    "author": "Jared Davidson",
                    "rating": "3.27",
                    "sys_updated_on": "2022-04-02 00:09:45",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What entity registration fields are available for different roles?",
                    "sys_id": "1ad10d7f1b75b0506e2dea02f54bcb9f",
                    "number": "KB0035802",
                    "_table_name": "kb_knowledge",
                    "text": "The linked PDF  provides a list of the fields in the SAM.gov entity registration domain that are viewable for four types of users: public users with no role, authenticated federal users, FOUO Entity Data Viewer, and Sensitive Entity Data Viewer. In addition,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Can I use my same login for FSD as SAM.gov?",
                    "sys_view_count": 33,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-04-02 00:05:32",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Can I use my same login for FSD as SAM.gov?",
                    "sys_id": "1d3f21e71b5a09d0cc45ea04bc4bcb44",
                    "number": "KB0056348",
                    "_table_name": "kb_knowledge",
                    "text": "Yes. You can sign in to both sites with the same login.gov account.",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I update my entity's NAICS Codes?",
                    "sys_view_count": 544,
                    "author": "Lilla Jimmerson",
                    "rating": "3.25",
                    "sys_updated_on": "2022-09-06 12:49:20",
                    "published": "2022-09-06",
                    "type": "kb_article",
                    "title": "How do I update my entity's NAICS Codes?",
                    "sys_id": "1e4e3fc51bf111540944ece0f54bcb14",
                    "number": "KB0016606",
                    "_table_name": "kb_knowledge",
                    "text": "To update an existing entity's NAICS Codes in SAM.gov: Navigate to SAM.gov. Select the “Sign In” button in the upper right corner. Select “Accept” to accept the US Government System terms. After selecting “Accept,” the system will direct you to login.gov....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What are the next steps now that we have updated our legal business name with SAM.gov?",
                    "sys_view_count": 1396,
                    "author": "Lilla Jimmerson",
                    "rating": "2.31",
                    "sys_updated_on": "2022-04-02 00:06:07",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What are the next steps now that we have updated our legal business name with SAM.gov?",
                    "sys_id": "1e7b29af1b9609d0cc45ea04bc4bcb20",
                    "number": "KB0016831",
                    "_table_name": "kb_knowledge",
                    "text": "After you submit your updated information in SAM.gov, if you have a Commercial and Government Entity (CAGE) code, the record will be sent to the Defense Logistics Agency (DLA) CAGE team for screening and validation. The CAGE team may contact your Government...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How can I view the Unique Entity ID of other entities?",
                    "sys_view_count": 3200,
                    "author": "Jared Davidson",
                    "rating": "3.25",
                    "sys_updated_on": "2022-08-23 15:04:30",
                    "published": "2022-08-23",
                    "type": "kb_article",
                    "title": "How can I view the Unique Entity ID of other entities?",
                    "sys_id": "1e7c4f071b1199502fe5ed7ae54bcbc7",
                    "number": "KB0041255",
                    "_table_name": "kb_knowledge",
                    "text": "The Unique Entity ID (UEI) is public as part of every entity record for entities that have opted into public search. Entities that have opted out of public search are viewable only by federal users and users with a role to the entity. You must sign in...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I confirm which users are authorized to access my entity registration in SAM.gov?",
                    "sys_view_count": 33,
                    "author": "Lilla Jimmerson",
                    "rating": "5",
                    "sys_updated_on": "2022-04-02 00:07:13",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I confirm which users are authorized to access my entity registration in SAM.gov?",
                    "sys_id": "1f0a21671b9609d0cc45ea04bc4bcb12",
                    "number": "KB0017412",
                    "_table_name": "kb_knowledge",
                    "text": "To view and confirm the users associated with your SAM.gov entity registration, follow the steps below: Sign in to SAM.gov. Navigate to your Workspace and locate the \"User Directory\" widget. Select the \"User Directory\" link to open the search menu. Filter...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I add documentation to my entity validation incident after it has been created in SAM.gov?",
                    "sys_view_count": 3889,
                    "author": "Jared Davidson",
                    "rating": "3.11",
                    "sys_updated_on": "2022-10-06 12:50:18",
                    "published": "2022-10-06",
                    "type": "kb_article",
                    "title": "How do I add documentation to my entity validation incident after it has been created in SAM.gov?",
                    "sys_id": "1fd279441bde9d1034b11179bc4bcbcc",
                    "number": "KB0057690",
                    "_table_name": "kb_knowledge",
                    "text": "Follow this guidance to ensure you have submitted the required documentation. If you discover that additional documentation is needed for your incident, follow these steps: Log in to SAM.gov. In your Workspace, select the title of the “Entities” pane...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What type of data is captured in the Representations and Certifications?",
                    "sys_view_count": 19,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-09-06 13:02:09",
                    "published": "2022-09-06",
                    "type": "kb_article",
                    "title": "What type of data is captured in the Representations and Certifications?",
                    "sys_id": "204180d11b3511540944ece0f54bcb42",
                    "number": "KB0016563",
                    "_table_name": "kb_knowledge",
                    "text": "For an entity wishing to compete for federal contracts, SAM.gov captures data regarding responses to FAR and, if applicable, DFARS and SF 330 Part II (A-E work) data. Some of the data prepopulates from data you, as the entity, provided in other areas...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What are NAICS Codes, and where do I find them?",
                    "sys_view_count": 181,
                    "author": "Lilla Jimmerson",
                    "rating": "5",
                    "sys_updated_on": "2022-07-12 15:57:03",
                    "published": "2022-07-12",
                    "type": "kb_article",
                    "title": "What are NAICS Codes, and where do I find them?",
                    "sys_id": "204318e91b109d500944ece0f54bcba4",
                    "number": "KB0016376",
                    "_table_name": "kb_knowledge",
                    "text": "The North American Industry Classification System (NAICS) is the standard used by the federal statistical agencies in classifying businesses for the purpose of analyzing, collecting, and publishing statistical data related to the U.S. economy. If you...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "When are the small business size standards for the 2017 NAICS Revision effective?",
                    "sys_view_count": 23,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-06-22 18:46:10",
                    "published": "2022-06-22",
                    "type": "kb_article",
                    "title": "When are the small business size standards for the 2017 NAICS Revision effective?",
                    "sys_id": "2227b1f01b9851500944ece0f54bcb4e",
                    "number": "KB0017307",
                    "_table_name": "kb_knowledge",
                    "text": "The U.S. Small Business Administration (SBA) updated its Table of Small Business Size Standards adopting the Office of Management and Budget's 2017 revision of the North American Industry Classification System (NAICS 2017 Revision) effective October 1,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Where can I find the notarized letter templates for SAM.gov?",
                    "sys_view_count": 315,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-09-14 17:16:49",
                    "published": "2022-09-14",
                    "type": "kb_article",
                    "title": "Where can I find the notarized letter templates for SAM.gov?",
                    "sys_id": "2338c2bb1b31d5d45465eaccac4bcb39",
                    "number": "KB0017350",
                    "_table_name": "kb_knowledge",
                    "text": "Read the instructions for domestic entities or instructions for international entities outlined in KB0016652.",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What information do I need to register my entity in SAM.gov?",
                    "sys_view_count": 538,
                    "author": "Lilla Jimmerson",
                    "rating": "3.86",
                    "sys_updated_on": "2022-04-02 00:07:08",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What information do I need to register my entity in SAM.gov?",
                    "sys_id": "24fe95af1bdec5d0cc45ea04bc4bcb3f",
                    "number": "KB0016844",
                    "_table_name": "kb_knowledge",
                    "text": "Depending on the type of registration you need, categories of information needed to register in SAM.gov may include the following:  Core Data: Includes, but is not limited to Unique Entity ID (which will be assigned during registration if the entity does...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I request a role on SAM.gov?",
                    "sys_view_count": 1179,
                    "author": "Lilla Jimmerson",
                    "rating": "3.33",
                    "sys_updated_on": "2022-03-31 16:58:51",
                    "published": "2022-03-31",
                    "type": "kb_article",
                    "title": "How do I request a role on SAM.gov?",
                    "sys_id": "25241eb21bb905d0fe314000f54bcb86",
                    "number": "KB0016602",
                    "_table_name": "kb_knowledge",
                    "text": "To access an entity registration record, you must be granted a role with an entity in SAM.gov by an Entity Administrator. To access the interested vendor list and controlled attachments on contract opportunity notices, you also need a role with your entity....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I check the status of an entity registration in SAM.gov?",
                    "sys_view_count": 11974,
                    "author": "Lilla Jimmerson",
                    "rating": "2.14",
                    "sys_updated_on": "2022-04-02 00:05:40",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I check the status of an entity registration in SAM.gov?",
                    "sys_id": "26c65d911b160550937fa64ce54bcbee",
                    "number": "KB0016313",
                    "_table_name": "kb_knowledge",
                    "text": "You may check the status of an entity registration when you are signed into your SAM.gov account and if you have a role assigned with the entity, or if your email address is recognized as a federal government email address. If neither of these is the...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What changes are being made to the Federal Entity Management?",
                    "sys_view_count": 39,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-02-05 02:14:45",
                    "published": "2022-02-05",
                    "type": "kb_article",
                    "title": "What changes are being made to the Federal Entity Management?",
                    "sys_id": "271419001b250154c5c4dd39bc4bcb5c",
                    "number": "KB0053795",
                    "_table_name": "kb_knowledge",
                    "text": "Select the link below to view and download the Federal Entity Management guide to learn more about what changes will be introduced on February 4, 2022 regarding the transition process from DUNS number to the Unique Entity ID (UEI): Federal Entity Management",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What do I need to do in SAM.gov in order to be eligible to register in Wide Area Workflow (WAWF) as a vendor?",
                    "sys_view_count": 65,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-02-15 19:59:57",
                    "published": "2022-02-15",
                    "type": "kb_article",
                    "title": "What do I need to do in SAM.gov in order to be eligible to register in Wide Area Workflow (WAWF) as a vendor?",
                    "sys_id": "2926c48c1b710d106397ec21f54bcb3c",
                    "number": "KB0020212",
                    "_table_name": "kb_knowledge",
                    "text": "Prior to registering in Wide Area Workflow (WAWF), all vendors must have an active registration in SAM. The Purpose of Registration must indicate “All Awards” in the System for Award Management (SAM.gov), and complete the Defense Federal Acquisition Regulation...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How can small businesses use SAM.gov?",
                    "sys_view_count": 119,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-08-25 13:39:45",
                    "published": "2022-08-25",
                    "type": "kb_article",
                    "title": "How can small businesses use SAM.gov?",
                    "sys_id": "2a9a05741b651d100ca4a97ae54bcb1f",
                    "number": "KB0061653",
                    "_table_name": "kb_knowledge",
                    "text": "Certified small businesses can use SAM.gov to:  Register to become eligible to receive federal financial assistance or contracts; Search for financial assistance programs or contract opportunities; Search for contract opportunities that use set-asides,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I indicate my entity is an Indian-ownded Economic Enterprise (IEE) or an Indian-owned Small Business Economic Enterprise (ISBEE) is in accorance with the Buy Indian Act?",
                    "sys_view_count": 24,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-08-26 15:10:21",
                    "published": "2022-08-26",
                    "type": "kb_article",
                    "title": "How do I indicate my entity is an Indian-ownded Economic Enterprise (IEE) or an Indian-owned Small Business Economic Enterprise (ISBEE) is in accorance with the Buy Indian Act?",
                    "sys_id": "2b057b651b215d50fe314000f54bcb1f",
                    "number": "KB0017792",
                    "_table_name": "kb_knowledge",
                    "text": "Indian-owned economic enterprise (IEE) must be an Indian-owned commercial, industrial, or business activity established or organized for the purpose of profit provided that such Indian ownership shall constitute not less than 51 percent of the enterprise....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "When will the IAE systems use the 2017 NAICS codes?",
                    "sys_view_count": 12,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-10-03 16:28:55",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "When will the IAE systems use the 2017 NAICS codes?",
                    "sys_id": "2c83bf791b12951406b09796bc4bcb16",
                    "number": "KB0016534",
                    "_table_name": "kb_knowledge",
                    "text": "The U.S. Census Bureau is the official source for the North American Industry Classification System (NAICS) structure. Their official NAICS homepage contains information on NAICS revisions, as well as access to various NAICS reference files and tools....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "I need to get a Unique Entity ID and it's after April 4. What should I do if my entity validation is not complete even though I started it with Dun & Bradstreet (D&B)?",
                    "sys_view_count": 214,
                    "author": "Lilla Jimmerson",
                    "rating": "2.66",
                    "sys_updated_on": "2022-04-02 00:10:15",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "I need to get a Unique Entity ID and it's after April 4. What should I do if my entity validation is not complete even though I started it with Dun & Bradstreet (D&B)?",
                    "sys_id": "2cbf2ade1be64d546e2dea02f54bcbd1",
                    "number": "KB0055129",
                    "_table_name": "kb_knowledge",
                    "text": "If your entity validation was not completed prior to the April 4 transition, start over in SAM.gov.  Choose Get Started to start a new registration and/or get your Unique Entity ID. This will trigger the validation process for your entity. The amount...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why do I have to enter the current bank information on my registration in order to change it?",
                    "sys_view_count": 90,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-08-18 16:37:49",
                    "published": "2022-08-18",
                    "type": "kb_article",
                    "title": "Why do I have to enter the current bank information on my registration in order to change it?",
                    "sys_id": "2e6c76031b1959502fe5ed7ae54bcb91",
                    "number": "KB0017541",
                    "_table_name": "kb_knowledge",
                    "text": "To further increase security and deter fraud, SAM.gov enhanced the data entry validation requirements on the Financial Information page. In order to change the bank account and routing number, the Entity Administrator must enter the current account and...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I update an existing entity registration in SAM.gov?",
                    "sys_view_count": 23044,
                    "author": "Lilla Jimmerson",
                    "rating": "2.76",
                    "sys_updated_on": "2022-04-02 00:10:33",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I update an existing entity registration in SAM.gov?",
                    "sys_id": "308b082b1b5201d0937fa64ce54bcb14",
                    "number": "KB0016307",
                    "_table_name": "kb_knowledge",
                    "text": "Note: If your SAM.gov Entity Administrator is no longer with the company or there is not an Entity Administrator associated with the registration, please create a user account and submit a Notarized Letter to gain access to update the existing registration....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I view the Quick Start Guide for Grant Registrants? ",
                    "sys_view_count": 65,
                    "author": "Jared Davidson",
                    "rating": "2.33",
                    "sys_updated_on": "2022-04-02 00:08:39",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How do I view the Quick Start Guide for Grant Registrants? ",
                    "sys_id": "32ac9d311baac554cc45ea04bc4bcbdd",
                    "number": "KB0029914",
                    "_table_name": "kb_knowledge",
                    "text": "Select the link below to download and view the Quick Start Guide for Grant Registrations:  Quick Start Guide - Grant Registrations",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Will I be able to sign in and use SAM.gov while the system is transitioning from DUNS Number to Unique Entity ID (SAM)?",
                    "sys_view_count": 2,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-03-05 18:23:37",
                    "published": "2022-03-05",
                    "type": "kb_article",
                    "title": "Will I be able to sign in and use SAM.gov while the system is transitioning from DUNS Number to Unique Entity ID (SAM)?",
                    "sys_id": "33a6dcbc1b42c914fe314000f54bcb6c",
                    "number": "KB0055139",
                    "_table_name": "kb_knowledge",
                    "text": "No. We expect system downtime across our entire portfolio (SAM.gov, FPDS.gov, eSRS.gov, FSRS.gov, FAPIIS.gov, and CPARS.gov). The downtime will occur the weekend prior to April 4, 2022, as we deploy the front-end and back-end changes to remove the DUNS...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why can't I see public entity data?",
                    "sys_view_count": 222,
                    "author": "Jared Davidson",
                    "rating": "1.35",
                    "sys_updated_on": "2022-07-19 17:05:36",
                    "published": "2022-07-19",
                    "type": "kb_article",
                    "title": "Why can't I see public entity data?",
                    "sys_id": "3413a8ad1bb05d10c5c4dd39bc4bcb1e",
                    "number": "KB0039522",
                    "_table_name": "kb_knowledge",
                    "text": "For any user to search or view entity registration data, you must be logged in. There are no roles required to view public data.",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why have I received an email requesting I provide a Notarized Letter to verify my financial information?",
                    "sys_view_count": 76,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-09-14 17:13:27",
                    "published": "2022-09-14",
                    "type": "kb_article",
                    "title": "Why have I received an email requesting I provide a Notarized Letter to verify my financial information?",
                    "sys_id": "367742f31b31d5d45465eaccac4bcb66",
                    "number": "KB0017327",
                    "_table_name": "kb_knowledge",
                    "text": "You are trying to register an entity which is part of a larger organization and there is no active Entity Administrator in the organization to review your request. You need to designate an Entity Administrator. SAM.gov requires a notarized letter to grant...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Using login.gov with SAM.gov",
                    "sys_view_count": 4548,
                    "author": "Lilla Jimmerson",
                    "rating": "2.66",
                    "sys_updated_on": "2022-10-03 18:05:30",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "Using login.gov with SAM.gov",
                    "sys_id": "3699c0061b1211546e2dea02f54bcb6c",
                    "number": "KB0017677",
                    "_table_name": "kb_knowledge",
                    "text": "The System for Award Management (SAM) uses login.gov for authentication when you log in. To link to the data you already have in SAM.gov, use the same email address for your login.gov account. If you want to change your email address, we recommend you...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Who has to have a CAGE code?",
                    "sys_view_count": 135,
                    "author": "Jared Davidson",
                    "rating": "",
                    "sys_updated_on": "2022-08-26 19:14:02",
                    "published": "2022-08-26",
                    "type": "kb_article",
                    "title": "Who has to have a CAGE code?",
                    "sys_id": "36dc60391b6d9d50fe314000f54bcb3c",
                    "number": "KB0045401",
                    "_table_name": "kb_knowledge",
                    "text": "At this time, every active registration in SAM.gov is required to have a Commercial and Government Entity (CAGE) code, issued by the Defense Logistics Agency (DLA).   Effective October 21, 2021, some SAM.gov registrations will no longer require assignment...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why is SAM.gov validating Taxpayer Identification Number (TIN) information with IRS?",
                    "sys_view_count": 30,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-10-03 17:56:16",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "Why is SAM.gov validating Taxpayer Identification Number (TIN) information with IRS?",
                    "sys_id": "3777000a1b9edd146e2dea02f54bcb23",
                    "number": "KB0016311",
                    "_table_name": "kb_knowledge",
                    "text": "The integrity of the data in SAM.gov is very important. The IRS is responsible for TIN information; therefor, they will validate TIN and taxpayer names. The TIN validation process in SAM.gov with the IRS ensures that TIN information is correctly entered...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "As a subcontractor or sub-recipient, how do I get a Unique Entity ID?",
                    "sys_view_count": 131,
                    "author": "Lilla Jimmerson",
                    "rating": "1.4",
                    "sys_updated_on": "2022-04-01 23:57:55",
                    "published": "2022-04-01",
                    "type": "kb_article",
                    "title": "As a subcontractor or sub-recipient, how do I get a Unique Entity ID?",
                    "sys_id": "3794447b1b42cdd40ca4a97ae54bcb41",
                    "number": "KB0045987",
                    "_table_name": "kb_knowledge",
                    "text": "If you are only getting a Unique Entity ID and not registering your entity in SAM.gov, then the process only requires you to provide basic information about your organization. An entity registration requires additional information about your organization,...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why do I have an alert on my entity that says \"Reset MPIN\" and what do I do?",
                    "sys_view_count": 520,
                    "author": "Jared Davidson",
                    "rating": "1.22",
                    "sys_updated_on": "2022-06-03 19:54:08",
                    "published": "2022-06-03",
                    "type": "kb_article",
                    "title": "Why do I have an alert on my entity that says \"Reset MPIN\" and what do I do?",
                    "sys_id": "37b300b21b7bcd543565ed3ce54bcb84",
                    "number": "KB0059154",
                    "_table_name": "kb_knowledge",
                    "text": "In May 2022, SAM.gov required entities to set a new Marketing Partner Identification Number (MPIN). If your entity MPIN needs to be reset, you will see an alert on the entity record in your Entities Workspace. To see the alert, follow the steps below:...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What does it mean for my entity to be included in public search?",
                    "sys_view_count": 396,
                    "author": "Lilla Jimmerson",
                    "rating": "3.53",
                    "sys_updated_on": "2022-08-10 20:36:10",
                    "published": "2022-08-10",
                    "type": "kb_article",
                    "title": "What does it mean for my entity to be included in public search?",
                    "sys_id": "37d081201b5d9d143565ed3ce54bcb30",
                    "number": "KB0017554",
                    "_table_name": "kb_knowledge",
                    "text": "After you validate your entity’s legal business name and address when getting a Unique Entity ID or starting a registration, you will be asked if you want your entity’s legal business name, physical address, and other non-sensitive information to be displayed...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "My entity is subject to FAR Subpart 4.18, but is a joint venture. How do I comply with FAR 52.204-17 which states I need to provide ownership details on each participant in the joint venture? ",
                    "sys_view_count": 43,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-08-26 15:09:46",
                    "published": "2022-08-26",
                    "type": "kb_article",
                    "title": "My entity is subject to FAR Subpart 4.18, but is a joint venture. How do I comply with FAR 52.204-17 which states I need to provide ownership details on each participant in the joint venture? ",
                    "sys_id": "37e4bf251b215d50fe314000f54bcb8d",
                    "number": "KB0017778",
                    "_table_name": "kb_knowledge",
                    "text": "Currently, only one Immediate Owner and one Highest-Level Owner may be identified in SAM.gov by a CAGE Code. If the offeror has more than one owner (such as a joint venture) at either level of ownership, they must select only one to report. This note...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Can I still register if I do not enter my entity's banking information?",
                    "sys_view_count": 50,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-07-24 23:54:01",
                    "published": "2022-07-24",
                    "type": "kb_article",
                    "title": "Can I still register if I do not enter my entity's banking information?",
                    "sys_id": "3b70334f1bb0d110c5c4dd39bc4bcb40",
                    "number": "KB0016397",
                    "_table_name": "kb_knowledge",
                    "text": "The banking information is mandatory for U.S. Registrants in SAM.gov, but it is optional for foreign/international registrants. This system ensures that payments are made to a current account. You are responsible for keeping your entity’s banking information...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How does the Unique Entity ID get assigned?",
                    "sys_view_count": 4214,
                    "author": "Jared Davidson",
                    "rating": "2.33",
                    "sys_updated_on": "2022-04-02 00:08:05",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "How does the Unique Entity ID get assigned?",
                    "sys_id": "3fcba40b1b0a01d40ca4a97ae54bcbd7",
                    "number": "KB0038428",
                    "_table_name": "kb_knowledge",
                    "text": "The Unique Entity ID is assigned automatically to entities when they request a Unique Entity ID or register on SAM.gov. You can refer to the video and user guide below for more information on how to get a Unique Entity ID:  Video: How to get only a Unique...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Why is SAM.gov stating my NCAGE Code does not exist when I register a new international entity?",
                    "sys_view_count": 72,
                    "author": "Lilla Jimmerson",
                    "rating": "4.33",
                    "sys_updated_on": "2022-07-19 17:06:38",
                    "published": "2022-07-19",
                    "type": "kb_article",
                    "title": "Why is SAM.gov stating my NCAGE Code does not exist when I register a new international entity?",
                    "sys_id": "405328651bf05d10c5c4dd39bc4bcb78",
                    "number": "KB0016955",
                    "_table_name": "kb_knowledge",
                    "text": "Before you can use your newly assigned NATO Commercial and Government Entity (NCAGE) Code to register in SAM.gov, it must be present in the U.S. CAGE database. If you are getting an error on the NCAGE Code page in SAM stating your NCAGE Code does not...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I filter by entity type?",
                    "sys_view_count": 3,
                    "author": "Jared Davidson",
                    "rating": "1",
                    "sys_updated_on": "2022-07-25 00:03:31",
                    "published": "2022-07-25",
                    "type": "kb_article",
                    "title": "How do I filter by entity type?",
                    "sys_id": "40b23f431bf0d110c5c4dd39bc4bcb09",
                    "number": "KB0029899",
                    "_table_name": "kb_knowledge",
                    "text": "Log in to your account and follow the instructions below: Navigate to the header menu of any page and select “Search.” From the search page, navigate to the left-side bar. Select the “plus” icon to the right of “Select Domain,” then select “Entity Registration...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I access the Disaster Response Registry? ",
                    "sys_view_count": 233,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-07-12 15:57:24",
                    "published": "2022-07-12",
                    "type": "kb_article",
                    "title": "How do I access the Disaster Response Registry? ",
                    "sys_id": "41ea58691b149d500944ece0f54bcbe2",
                    "number": "KB0053527",
                    "_table_name": "kb_knowledge",
                    "text": "The Guide to Searching the Disaster Response Registry is to help you access and search the Disaster Response Registry. To download and view the Guide to Searching the Disaster Response Registry, click the link below: Guide to Searching the Disaster Response...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I remove a user's access from an entity registration?",
                    "sys_view_count": 111,
                    "author": "Lilla Jimmerson",
                    "rating": "3",
                    "sys_updated_on": "2022-10-03 18:01:04",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "How do I remove a user's access from an entity registration?",
                    "sys_id": "429880461bdedd146e2dea02f54bcb0d",
                    "number": "KB0017411",
                    "_table_name": "kb_knowledge",
                    "text": "To remove a user’s access from your entity registration in SAM.gov, follow the steps below: Log into your SAM.gov user account. You will be taken to your Workspace. Locate the \"User Directory\" widget. Here you will be able to view and search for users...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "I manage a system that pulls SAM.gov data through an API or extract. What should I do to prepare for entities without a CAGE code?",
                    "sys_view_count": 3,
                    "author": "Jared Davidson",
                    "rating": "",
                    "sys_updated_on": "2022-10-03 16:35:42",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "I manage a system that pulls SAM.gov data through an API or extract. What should I do to prepare for entities without a CAGE code?",
                    "sys_id": "4505bf751b52951406b09796bc4bcba0",
                    "number": "KB0045402",
                    "_table_name": "kb_knowledge",
                    "text": "Changes will be made effective October 21, 2021, resulting in a population of entities without a CAGE code. For these entities, the CAGE code field in all extracts will be blank (empty). All system administrators who consume SAM.gov data need to check...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What to do if your entity is shown in the results, but has some incorrect info",
                    "sys_view_count": 149,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-09-13 12:50:11",
                    "published": "2022-09-13",
                    "type": "kb_article",
                    "title": "What to do if your entity is shown in the results, but has some incorrect info",
                    "sys_id": "457b23731badd5d00ca4a97ae54bcbb2",
                    "number": "KB0061910",
                    "_table_name": "kb_knowledge",
                    "text": "These are the instructions for 3. What to Do If Your Entity Is in Results, but Has Some Incorrect Info Previous Entity Validation Steps:  Starting as a New Entity in SAM.gov  Starting as an Entity Already in SAM.gov  Enter your Entity Information and...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I filter entity registrations by socio-economic status? ",
                    "sys_view_count": 37,
                    "author": "Jared Davidson",
                    "rating": "2.75",
                    "sys_updated_on": "2022-10-03 17:58:20",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "How do I filter entity registrations by socio-economic status? ",
                    "sys_id": "46f74c0e1b9edd146e2dea02f54bcb00",
                    "number": "KB0029901",
                    "_table_name": "kb_knowledge",
                    "text": "Log in to your account and follow the instructions below: Navigate to the header menu of any page and select “Search.” From the search page, navigate to the left-side bar. Select the “plus” icon to the right of “Select Domain,” then select “Entity Registration...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I access the Quick Start Guide for Contract Registrations? ",
                    "sys_view_count": 101,
                    "author": "Jared Davidson",
                    "rating": "4.5",
                    "sys_updated_on": "2022-08-10 14:07:04",
                    "published": "2022-08-10",
                    "type": "kb_article",
                    "title": "How do I access the Quick Start Guide for Contract Registrations? ",
                    "sys_id": "47b14d241b5d9d143565ed3ce54bcbe2",
                    "number": "KB0029913",
                    "_table_name": "kb_knowledge",
                    "text": "Select the link below to download and view the Quick Start Guide for Contract Registrations:  Quick Start Guide - Contract Registrations",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I find and report the CAGE Code for my entity's Immediate Owner?",
                    "sys_view_count": 77,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-09-21 20:26:40",
                    "published": "2022-09-21",
                    "type": "kb_article",
                    "title": "How do I find and report the CAGE Code for my entity's Immediate Owner?",
                    "sys_id": "47d6f68e1b8ed15006b09796bc4bcba6",
                    "number": "KB0016989",
                    "_table_name": "kb_knowledge",
                    "text": "If you know the CAGE Code of your entity’s Immediate Owner, you must enter and verify it on the CAGE Ownership Details page in SAM.gov. SAM.gov will show you the Legal Business Name and Physical Address associated with the CAGE Code you provided so you...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What are representations and certifications?",
                    "sys_view_count": 242,
                    "author": "Lilla Jimmerson",
                    "rating": "2.08",
                    "sys_updated_on": "2022-09-06 15:26:14",
                    "published": "2021-06-24",
                    "type": "kb_article",
                    "title": "What are representations and certifications?",
                    "sys_id": "4808c1001b4538905465eaccac4bcb7c",
                    "number": "KB0016553",
                    "_table_name": "kb_knowledge",
                    "text": "If you are registering in SAM.gov to pursue federal contracts, grants, or other procurement opportunities, you must complete the Representations and Certifications (Reps and Certs) section. Complying with the Federal Acquisition Regulation (FAR) Subpart...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How long does it take to get an NCAGE Code?",
                    "sys_view_count": 41,
                    "author": "Lilla Jimmerson",
                    "rating": "1",
                    "sys_updated_on": "2022-09-21 20:27:51",
                    "published": "2022-09-21",
                    "type": "kb_article",
                    "title": "How long does it take to get an NCAGE Code?",
                    "sys_id": "4c27b6021bced15006b09796bc4bcb94",
                    "number": "KB0016995",
                    "_table_name": "kb_knowledge",
                    "text": "You can review instructions tailored for international registrants and information about the NCAGE Code assignment process here",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What is the Taxpayer Identification Number (TIN) process?",
                    "sys_view_count": 200,
                    "author": "Lilla Jimmerson",
                    "rating": "5",
                    "sys_updated_on": "2022-09-06 12:49:50",
                    "published": "2022-09-06",
                    "type": "kb_article",
                    "title": "What is the Taxpayer Identification Number (TIN) process?",
                    "sys_id": "4c7e73091bf111540944ece0f54bcb53",
                    "number": "KB0016540",
                    "_table_name": "kb_knowledge",
                    "text": "To have an active registration in SAM.gov, you must authorize the Internal Revenue Service (IRS) to validate that the Taxpayer Identification Name and Taxpayer Identification Number (TIN) (Employer Identification Number or Social Security Number) provided...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How do I search entity registrations in SAM.gov? ",
                    "sys_view_count": 1778,
                    "author": "Jared Davidson",
                    "rating": "2.15",
                    "sys_updated_on": "2022-04-08 20:26:07",
                    "published": "2022-04-08",
                    "type": "kb_article",
                    "title": "How do I search entity registrations in SAM.gov? ",
                    "sys_id": "4d6c50571b1a4d90937fa64ce54bcbfd",
                    "number": "KB0029894",
                    "_table_name": "kb_knowledge",
                    "text": "Sign in to your SAM.gov account and follow the instructions below: From the homepage, select “Entity Information.” Entity Information includes exclusions, ID assigned entities, and entities with existing registrations. You can use these filters to select...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "Video: Entity Registration - Core Data ",
                    "sys_view_count": 43,
                    "author": "Lilla Jimmerson",
                    "rating": "3",
                    "sys_updated_on": "2022-04-02 00:09:42",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "Video: Entity Registration - Core Data ",
                    "sys_id": "4dfc0a451be2451406b09796bc4bcb73",
                    "number": "KB0056710",
                    "_table_name": "kb_knowledge",
                    "text": "This video walks through the core data section of an entity registration in SAM.gov for non-federal entities.",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "I manage an entity in SAM.gov. What do I need to do for the change from the DUNS Number to the Unique Entity ID?",
                    "sys_view_count": 12756,
                    "author": "Jared Davidson",
                    "rating": "3.41",
                    "sys_updated_on": "2022-08-10 14:05:14",
                    "published": "2022-08-10",
                    "type": "kb_article",
                    "title": "I manage an entity in SAM.gov. What do I need to do for the change from the DUNS Number to the Unique Entity ID?",
                    "sys_id": "4e9325981bd1d154860e62cfe54bcbf2",
                    "number": "KB0055533",
                    "_table_name": "kb_knowledge",
                    "text": "If you are an Entity Administrator who is transitioning from using a DUNS Number to using the Unique Entity ID, here is what you need to do. To find your Unique Entity ID(s), sign in to SAM.gov and go to your Workspace (the link is in the subheader menu)....",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What happened to DUNS +4 number registrations? ",
                    "sys_view_count": 31,
                    "author": "Lilla Jimmerson",
                    "rating": "",
                    "sys_updated_on": "2022-04-02 00:07:45",
                    "published": "2022-04-02",
                    "type": "kb_article",
                    "title": "What happened to DUNS +4 number registrations? ",
                    "sys_id": "501b145b1bd64d90937fa64ce54bcbfe",
                    "number": "KB0052957",
                    "_table_name": "kb_knowledge",
                    "text": "We retired the term \"DUNS+4\" in SAM.gov to align with policy. The new term is Electronic Funds Transfer (EFT) Indicator. If you need to add more than one set of financial information to your entity registration, you select a combination of four numbers...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "What are size standards, and what determines whether I am a small business or not?",
                    "sys_view_count": 106,
                    "author": "Lilla Jimmerson",
                    "rating": "2",
                    "sys_updated_on": "2022-03-03 20:28:49",
                    "published": "2022-03-03",
                    "type": "kb_article",
                    "title": "What are size standards, and what determines whether I am a small business or not?",
                    "sys_id": "5026ae0d1bce41542fe5ed7ae54bcb1c",
                    "number": "KB0016391",
                    "_table_name": "kb_knowledge",
                    "text": "Size Standards are numerical thresholds that a registrant must meet in order to qualify as a small business for a certain industry classification set by the Small Business Administration (SBA). SAM.gov displays SBA's indication of whether your organization...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                },
                {
                    "short_description": "How are sub-recipients or subcontractors impacted by the change from DUNS Number to Unique Entity ID?",
                    "sys_view_count": 386,
                    "author": "Lilla Jimmerson",
                    "rating": "2.73",
                    "sys_updated_on": "2022-10-03 18:13:53",
                    "published": "2022-10-03",
                    "type": "kb_article",
                    "title": "How are sub-recipients or subcontractors impacted by the change from DUNS Number to Unique Entity ID?",
                    "sys_id": "502b484a1b5211546e2dea02f54bcb03",
                    "number": "KB0045986",
                    "_table_name": "kb_knowledge",
                    "text": "For sub-awardees, including subcontractors: If your prime is required to report on subcontracting dollars, you will need a Unique Entity ID before April 4, 2022. Your prime cannot request a Unique Entity ID on your behalf. Depending on what selection...",
                    "kb_category": "7ae0cb0c1b4f64108aa3a8eae54bcb0e"
                }
            ];
